# AUTOGENERATED! DO NOT EDIT! File to edit: ../app.ipynb.

# %% auto 0
__all__ = ['path_to_pkl_model', 'learn', 'categories', 'image', 'label', 'intf', 'classify_image']

# %% ../app.ipynb 3
from fastai.vision.all import *
import gradio as gr
path_to_pkl_model = '/workspace/models/model_epoch20.pkl'

# %% ../app.ipynb 5
learn = load_learner(path_to_pkl_model)

# %% ../app.ipynb 10
categories = learn.dls.vocab # learn.dls.vocab provides the categories from our trained model

def classify_image(img):
    img = PILImage.create(img).resize((192, 192))
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))

# %% ../app.ipynb 13
image = gr.Image()
label = gr.Label()

intf = gr.Interface(fn=classify_image, inputs=image, outputs=label)
intf.launch(inline=False)
